### PR TITLE
Add Java 20

### PR DESCRIPTION
**Pull request by blaenk**
Modeled after #204

### CODE REVIEW

**Comment by pivotal-david-osullivan** [comment]
Thanks for the PR @blaenk! It looks good, but going forward we've decided to replace the short-term release in the JVM provider buildpacks, rather than having 2 overlap. If you could please add a change to remove 19 while adding 20, similar to https://github.com/paketo-buildpacks/bellsoft-liberica/pull/383/files, we can get this merged!

**Comment by blaenk** [comment]
Sure I'll do that when I get a chance if someone doesn't get to it first.

By the way, if someone specifies `BP_JVM_VERSION` to `19` then I guess things will break? Assuming they're using `gcr.io/paketo-buildpacks/amazon-corretto:latest`?

Does that mean that one shouldn't pin to `:latest`? Or what is the idea here? Should I not be pinning `BP_JVM_VERSION`?

Making sure I don't get myself into that situation.

**Review by pivotal-david-osullivan — APPROVED** [review]

**Comment by pivotal-david-osullivan** [comment]
Thank you @blaenk! To answer your question regarding 19, that is correct. The idea being that it's probably best to pin to the latest LTS version (i.e. 17 currently, with no need to manually pin since it's now the default), and users can specify short-term releases for exploring new features etc. It's definitely best then to use the `:latest` of the buildpack itself to get patches/maintenance updates etc.

**Comment by pivotal-david-osullivan** [comment]
Thank you @blaenk! To answer your question regarding 19, that is correct. The idea being that it's probably best to pin to the latest LTS version (i.e. 17 currently, with no need to manually pin since it's now the default), and users can specify short-term releases for exploring new features etc. It's definitely best then to use the `:latest` of the buildpack itself to get patches/maintenance updates etc.

**Pull request merged**
